export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const BAD_REQUEST = 'BAD_REQUEST';
export const NOT_FOUND = 'NOT_FOUND';
export const INVALID_FORMAT = 'INVALID_FORMAT';
export const CONFLICT = 'CONFLICT';
